config/routes.rb
Verbabo::Application.routes.draw do
  get "comments/new"
  resources :thread_boards
  resources :comments
  get "thread_boards/new"
  get "thread_boards/home"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :thread_board, class_name: 'ThreadBoard'
	validates :name, presence: true
	validates :comment, presence: true

end

app/models/thread_board.rb
class ThreadBoard < ActiveRecord::Base
	validates :title, presence: true
    has_many :comments, dependent: :destroy, class_name: 'Comment'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    logger.debug('fuck')
  end

  def create
  	@comment = Comment.new(comment_params)
  	@comment.save


    @threadBoard = ThreadBoard.find(params[:comment][:thread_board_id])
    @comments = @threadBoard.comments
    @comment = Comment.new
    redirect_to @threadBoard
  end


  private
	  def comment_params
        params[:comment].permit(:name, :comment, :thread_board_id);
      end  
end

app/controllers/thread_boards_controller.rb
class ThreadBoardsController < ApplicationController
  def create 
  	@threadBoard = ThreadBoard.new(thread_params)
  	if @threadBoard.save
  	  redirect_to :action => "index"
  	else
  	  #fail create thread
  	  redirect_to :action => "index"
 	end
  end

  def new
  end

  def create_new_comment
    @comment = Comment.new(comment_params)
    @comment.save


    redirect_to :action => "show"
#    @threadBoard = ThreadBoard.find(params[:thread_board_id])

#    @comments = @threadBoard.comments
#    @comment = Comment.new


  end

  def show
  	@threadBoard = ThreadBoard.find(params[:id])
    @comments = @threadBoard.comments
    @comment = Comment.new

  end

  def index
  	@threadBoards = ThreadBoard.all
  	@threadBoard = ThreadBoard.new
  end

  private
	  def thread_params
        params[:thread_board].permit(:title);
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/thread_boards_helper.rb
module ThreadBoardsHelper
end

app/views/comments/create.html.erb
<html>
<head>
	<meta http-equiv="Refresh" content="thread_boards/2">

</head>
<body>

</body>
</html>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Verbabo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thread_boards/home.html.erb
<!DOCTYPE html>

<html>
<body>
<div>tests</div>
</body>
</html>

app/views/thread_boards/index.html.erb
<html>
<body>
	<%= form_for(@threadBoard) do | f | %>
		<%= f.label :title %>
		<%= f.text_field :title %>

		<%= f.submit "Create new thread!" %>
	<% end %>


	<% @threadBoards.each do | threadboard | %>
		<div>
			<%= link_to threadboard.title, thread_board_path(threadboard.id) %>
			<%= threadboard.title %>
		</div>
	<% end %>

	<%= debug(params) %>

</body>
</html>

app/views/thread_boards/new.html.erb
<h1>ThreadBoards#new</h1>
<p>Find me in app/views/thread_boards/new.html.erb</p>

app/views/thread_boards/show.html.erb
<html>
<body>
	<div id="container">
	<table>
	<% @comments.each do | comment | %>
		<tr>
			<td class="username">
			<%= comment.name %>
			</td>
			<td class=comment>
			「<%= comment.comment %>」
			</td>
		</tr>
	<% end %>


	</table>
	</div>



	<div id="footer">
		<div style="margin-left:auto;margin-right:auto;width:70%">
			<hr>
		</div>
		<div style="margin-left:auto;margin-right:auto;width:30em">



		<%= form_for(@comment) do | f | %>
			<%= f.text_field :name %><br>
			<%= f.text_area :comment, :size => "50x2"%>
			<%= f.hidden_field :thread_board_id, :value => @threadBoard.id%>


			<%= f.submit "書き込む" %>
		<% end %>

		</div>
	</div>

</body>
</html>